name: ❓ Question
description: Ask a question about Takumi usage
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Before asking, please check:
        - [Documentation](https://takumi.kane.tw/docs)
        - [Playground](https://takumi.kane.tw/playground)
        - [Existing issues](https://github.com/kane50613/takumi/issues?q=is%3Aissue)

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any code or context that helps explain your question

  - type: textarea
    id: tried
    attributes:
      label: What I've Tried
      description: What have you already tried or researched?
