mod test_utils;

#[path = "fixtures/animation.rs"]
pub mod animation;
#[path = "fixtures/color_artifacts.rs"]
pub mod color_artifacts;
#[path = "fixtures/inline.rs"]
pub mod inline;
#[path = "fixtures/inline_vertical_align.rs"]
pub mod inline_vertical_align;
#[path = "fixtures/style_alignment.rs"]
pub mod style_alignment;
#[path = "fixtures/style_backdrop_filter.rs"]
pub mod style_backdrop_filter;
#[path = "fixtures/style_background_clip.rs"]
pub mod style_background_clip;
#[path = "fixtures/style_background_image.rs"]
pub mod style_background_image;
#[path = "fixtures/style_clip_path.rs"]
pub mod style_clip_path;
#[path = "fixtures/style_filter.rs"]
pub mod style_filter;
#[path = "fixtures/style_layout.rs"]
pub mod style_layout;
#[path = "fixtures/style_mask_image.rs"]
pub mod style_mask_image;
#[path = "fixtures/style_mix_blend_mode.rs"]
pub mod style_mix_blend_mode;
#[path = "fixtures/style_object_fit.rs"]
pub mod style_object_fit;
#[path = "fixtures/style_object_position.rs"]
pub mod style_object_position;
#[path = "fixtures/style_opacity.rs"]
pub mod style_opacity;
#[path = "fixtures/style_overflow.rs"]
pub mod style_overflow;
#[path = "fixtures/style_padding.rs"]
pub mod style_padding;
#[path = "fixtures/style_position.rs"]
pub mod style_position;
#[path = "fixtures/style_sizing.rs"]
pub mod style_sizing;
#[path = "fixtures/style_spacing.rs"]
pub mod style_spacing;
#[path = "fixtures/style_text_decoration.rs"]
pub mod style_text_decoration;
#[path = "fixtures/style_text_decoration_thickness.rs"]
pub mod style_text_decoration_thickness;
#[path = "fixtures/style_transform.rs"]
pub mod style_transform;
#[path = "fixtures/style_visuals.rs"]
pub mod style_visuals;
#[path = "fixtures/svg.rs"]
pub mod svg;
#[path = "fixtures/text.rs"]
pub mod text;
