// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PositionComponent } from "./PositionComponent";
import type { SpacePair } from "./SpacePair";

/**
 * Parsed `background-position` value for one layer.
 */
export type BackgroundPosition = SpacePair<PositionComponent>;
