// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackgroundRepeatStyle } from "./BackgroundRepeatStyle";

/**
 * Combined repeat for X and Y axes.
 */
export type BackgroundRepeat = [BackgroundRepeatStyle, BackgroundRepeatStyle];
