// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapePosition } from "./ShapePosition";
import type { ShapeRadius } from "./ShapeRadius";

/**
 * Represents a circle() shape.
 */
export type CircleShape = {
  /**
   * The radius of the circle
   */
  radius: ShapeRadius;
  /**
   * The center position of the circle
   */
  position: ShapePosition;
};
