// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapePosition } from "./ShapePosition";
import type { ShapeRadius } from "./ShapeRadius";

/**
 * Represents an ellipse() shape.
 */
export type EllipseShape = {
  /**
   * The horizontal radius
   */
  radiusX: ShapeRadius;
  /**
   * The vertical radius
   */
  radiusY: ShapeRadius;
  /**
   * The center position of the ellipse
   */
  position: ShapePosition;
};
