// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the fill rule used for determining the interior of shapes.
 *
 * Corresponds to the SVG fill-rule attribute and is used in polygon(), path(), and shape() functions.
 */
export type FillRule = "non-zero" | "even-odd";
