// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the direction of the grid auto flow.
 */
export type GridDirection = "row" | "column";
