// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridDirection } from "./GridDirection";

/**
 * Represents the flow of the grid auto placement.
 */
export type GridAutoFlow =
  | { direction: GridDirection; dense: boolean }
  | string;
