// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LengthUnit } from "./LengthUnit";
import type { Sides } from "./Sides";

/**
 * Represents an inset() rectangle shape.
 *
 * The inset() function creates an inset rectangle, with its size defined by the offset distance
 * of each of the four sides of its container and, optionally, rounded corners.
 */
export type InsetShape = {
  /**
   * Sides of the inset.
   */
  inset: Sides<LengthUnit>;
  /**
   * Optional border radius for rounded corners
   */
  borderRadius: Sides<LengthUnit> | null;
};
