// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How children overflowing their container should affect layout
 */
export type Overflow = "visible" | "hidden";
