// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Overflow } from "./Overflow";
import type { SpacePair } from "./SpacePair";

/**
 * Represents overflow values for both axes.
 *
 * Can be either a single value applied to both axes, or separate values
 * for horizontal and vertical overflow.
 */
export type Overflows = SpacePair<Overflow>;
