// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Overflow } from "./Overflow";

/**
 * Represents overflow values for both axes.
 *
 * Can be either a single value applied to both axes, or separate values
 * for horizontal and vertical overflow.
 */
export type Overflows = Overflow | [Overflow, Overflow] | string;
