// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FillRule } from "./FillRule";

/**
 * Represents a path() shape using an SVG path string.
 */
export type PathShape = {
  /**
   * The fill rule to use
   */
  fillRule: FillRule | null;
  /**
   * SVG path data string
   */
  path: string;
};
