// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LengthUnit } from "./LengthUnit";

/**
 * Represents a single coordinate pair in a polygon.
 */
export type PolygonCoordinate = {
  /**
   * X coordinate
   */
  x: LengthUnit;
  /**
   * Y coordinate
   */
  y: LengthUnit;
};
