// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FillRule } from "./FillRule";
import type { PolygonCoordinate } from "./PolygonCoordinate";

/**
 * Represents a polygon() shape.
 */
export type PolygonShape = {
  /**
   * The fill rule to use
   */
  fillRule: FillRule | null;
  /**
   * List of coordinate pairs defining the polygon vertices
   */
  coordinates: Array<PolygonCoordinate>;
};
