// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LengthUnit } from "./LengthUnit";
import type { SpacePair } from "./SpacePair";

/**
 * Represents a position for circle() and ellipse() functions.
 */
export type ShapePosition = SpacePair<LengthUnit>;
