// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LengthUnit } from "./LengthUnit";

/**
 * Represents radius values for circle() and ellipse() functions.
 */
export type ShapeRadius = "closest-side" | "farthest-side" | LengthUnit;
