// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A pair of values for horizontal and vertical axes.
 */
export type SpacePair<T> = T | { x: T; y: T } | string;
