// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextDecorationLine } from "./TextDecorationLine";

/**
 * Represents a collection of text decoration lines.
 */
export type TextDecorationLines = Array<TextDecorationLine> | string;
