// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents text decoration line options.
 */
export type TextDecorationLine = "underline" | "line-through" | "overline";
